# Generated by Django 4.2.7 on 2023-12-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_meta_name_job_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
    ]
