version: "3.4"
services:
  database:
    image: postgres:14.2
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "app" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 1s
    container_name: jobs_platform_database
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - ./jobs_platform:/home/dev/jobs_platform
    depends_on:
      - database
    command: bash -c "pip install -r /home/dev/jobs_platform/requirements.txt && cd jobs_platform && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - PATH=$PATH:/home/dev/.local/bin
    tty: true
    stdin_open: true
    container_name: jobs_platform_api